---
- hosts: master, worker
  become: true
  tasks:
  - name: add packages repo and key
    shell: |
      # https://docs.docker.com/engine/install/ubuntu/#install-from-a-package
      apt-get install -y ca-certificates curl gnupg
      mkdir -m 0755 -p /etc/apt/keyrings
      curl -fsSLo /etc/apt/keyrings/docker.gpg https://download.docker.com/linux/ubuntu/gpg
      echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/docker.list

      # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
      curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - name: kubernetes install
    apt:
      name:
      - containerd.io
      - docker-ce
      - kubectl
      - kubeadm
      - kubelet
      state: present
  - name: configure containerd
    shell: |
      sed -i /disabled_plugins/d /etc/containerd/config.toml
      systemctl restart containerd
  - name: create cluster
    command: kubeadm init
    when: ansible_hostname is search('master')
  - name: create cluster
    command: kubeadm token create --print-join-command
    when: ansible_hostname is search('master')
  - name: join cluster
    command: "{{ join.stdout }}"
    when: ansible_hostname is search('worker')
